name: Release

on:
  workflow_dispatch: # disabled on push – not needed in fork

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
      versionTag: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          registry-url: https://registry.npmjs.org
      - name: Update npm to latest version
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: npm publish --provenance --access public
      - name: Extract version from publishedPackages
        id: version
        run: |
          echo "VERSION=$(echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -r '.[0].version')" >> $GITHUB_OUTPUT

  docker-publish:
    needs: release
    if: needs.release.outputs.hasChangesets == 'false'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yml
    with:
      versionTag: ${{ needs.release.outputs.versionTag }}
    secrets: inherit
